### ISSUE TITLE
Unable to deploy on Heroku

### ISSUE THREAD

**Issue by EPFLRQN** [synzen/Discord.RSS-Web#1]
![image](https://user-images.githubusercontent.com/45467260/77826853-0c3d8400-714d-11ea-8b8b-2442be548d44.png)

**Comment by synzen** [comment]
Thanks for the report, should be fixed in https://github.com/synzen/Discord.RSS-Web/commit/14a908602d24117adecfcf119d1d0dc29fc9e7ff

**Comment by EPFLRQN** [comment]
![image](https://user-images.githubusercontent.com/45467260/79484238-ef0e1e00-8045-11ea-84c4-6d16d19c0a11.png)
